exports.FONTS_SANS = [
  '"IBM Plex Sans"',
  '"-apple-system"',
  "'BlinkMacSystemFont'",
  "'Helvetica Neue'",
  "'PingFang SC'",
  "'Microsoft YaHei'",
  "'Source Han Sans SC'",
  "'Noto Sans CJK SC'",
  "'WenQuanYi Micro Hei'",
  "'sans-serif'"
]
exports.FONTS_SERIF = [
  '"Source Serif"',
  'ui-serif',
  'Georgia',
  '"Nimbus Roman No9 L"',
  '"Songti SC"',
  '"Noto Serif CJK SC"',
  '"Source Han Serif SC"',
  '"Source Han Serif CN"',
  'STSong',
  '"AR PL New Sung"',
  '"AR PL SungtiL GB"',
  'NSimSun',
  'SimSun',
  '"TW-Sung"',
  '"WenQuanYi Bitmap Song"',
  '"AR PL UMing CN"',
  '"AR PL UMing HK"',
  '"AR PL UMing TW"',
  '"AR PL UMing TW MBE"',
  'PMingLiU',
  'MingLiU',
  'serif'
]
